### ISSUE TITLE
Expand check on 'environment' argument for BaseClient class

### ISSUE THREAD

**Issue by appukuttan-shailesh** [apdavison/hbp-validation-client#15]
The `environment` argument for the `BaseClient` class currently accepts only 'production' and 'dev' as valid values. This should be extended to allow users to specify their own values. Parameters appropriate for these would then be read from an external config file.

**Comment by appukuttan-shailesh** [comment]
@apdavison : is the following structure fine for the config file?

```
{
  "dev1": {
      "url": "www.....",
      "client_id": ""
  },
  "dev2": {
      "url": "www.....",
      "client_id": ""
  }
  ...
}
```
Do you foresee the need for any other parameters here at this point?
username, password?

**Comment by apdavison** [comment]
Looks fine to me. We can always add further parameters later.

**Comment by appukuttan-shailesh** [comment]
This is the method header currently:
`def __init__(self, username,
                 password=None,
                 environment="production"):`

We plan to access the config file for any values of `environment` apart from "environment" and "dev". Should we force a name and location for the config file (such as `environ.json` in the current directory), or  add some new parameter for specifying the config path?

**Comment by appukuttan-shailesh** [comment]
p.s. I propose we move even the "environment" and "dev" info to this config file. So all environment info is gathered from the config file. Easier

**Comment by apdavison** [comment]
I suggest `config.json` in the current directory.
